language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      sudo: required

addons:
  apt:
    packages:
      - git
      - mercurial
      - cmake
      - libpng-dev
      - libjpeg-dev
      - libtiff-dev
      - libglu1-mesa-dev
      - libboost-iostreams-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-serialization-dev
      - libopencv-dev
      - libcgal-dev
      - libatlas-base-dev
      - libsuitesparse-dev
      - freeglut3-dev
      - libglew-dev
      - libglfw3-dev

before_install:
  - echo $LANG
  - export OMP_NUM_THREADS=4

install:
  ### Common
  # Install the latest version of VCG
  - git clone https://github.com/cdcseacave/VCG.git /tmp/vcglib
  ### LINUX
  # Install the latest version of Eigen
  - if [ $TRAVIS_OS_NAME == linux ]; then hg clone https://bitbucket.org/eigen/eigen#3.2 /tmp/eigen && mkdir /tmp/eigen-build && cd /tmp/eigen-build && cmake . /tmp/eigen && make && sudo make install && cd -; fi
  # Install the latest version of Ceres Solver
  - if [ $TRAVIS_OS_NAME == linux ]; then git clone --branch=master git://github.com/ceres-solver/ceres-solver.git /tmp/ceres-solver && mkdir /tmp/ceres-solver-build && cd /tmp/ceres-solver-build && cmake /tmp/ceres-solver -DMINIGLOG=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF && make -j4 && sudo make install && cd -; fi
  ### OSX
  # Install dependencies
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew tap homebrew/science && brew install boost eigen opencv cgal ceres-solver; fi

before_script:
  - cd ..
  - mkdir build
  - cd build
  - cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="/tmp/vcglib"

script:
  - make -j4

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

branches:
  only:
    - master
    - develop

notifications:
  email: true
